# Generated by Django 6.0.7 on 2026-07-14 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsadmin', '0002_remove_book_authors_book_authors'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('member', 'book')},
        ),
    ]
